import type { Locale } from "./i18n";

const en = {
  loginTitle: "Your dossier, one email away",
  loginSub: "We'll send you a sign-in link — no password to remember, no data stored until you're in.",
  emailPlaceholder: "you@example.com",
  sendLink: "Send me a sign-in link",
  linkSent: "Check your inbox — your sign-in link is on its way.",
  setupNeeded: "The dossier backend isn't configured yet. Add the Supabase environment variables and redeploy.",
  dashboardTitle: "Your dossier",
  progress: "documents ready",
  pickPathway: "Choose the visa you're preparing",
  startDossier: "Start my dossier",
  statusLabels: {
    missing: "To upload",
    uploaded: "Uploaded",
    in_review: "In review",
    needs_fix: "Needs a fix",
    accepted: "Accepted",
  } as Record<string, string>,
  upload: "Upload",
  replace: "Replace",
  apostille: "Apostille required",
  translation: "Sworn translation required",
  validity: (days: number) => `Valid ${days} days — order with timing in mind`,
  perDependent: "One per family member",
  formLabel: "Application form",
  feeLabel: "Government fee",
  reviewNote: "Uploaded documents are queued for validation. Automated checks arrive in the next release — for now our team reviews uploads during the beta.",
  vaultNote: "Files are stored encrypted in an EU (Frankfurt) data centre, in a private folder only your account can access. Delete your account and everything goes with it.",
  signOut: "Sign out",
  deleteDoc: "Remove",
  supervised: "Checklist v2026-07 · maintained under colegiado supervision",
  backHome: "Back to luma.legal",
};

const es: typeof en = {
  loginTitle: "Tu expediente, a un email de distancia",
  loginSub: "Te enviamos un enlace de acceso — sin contraseñas que recordar y sin guardar datos hasta que entres.",
  emailPlaceholder: "tu@ejemplo.com",
  sendLink: "Enviarme el enlace de acceso",
  linkSent: "Revisa tu correo — tu enlace de acceso está en camino.",
  setupNeeded: "El backend del expediente aún no está configurado. Añade las variables de entorno de Supabase y vuelve a desplegar.",
  dashboardTitle: "Tu expediente",
  progress: "documentos listos",
  pickPathway: "Elige el visado que estás preparando",
  startDossier: "Empezar mi expediente",
  statusLabels: {
    missing: "Por subir",
    uploaded: "Subido",
    in_review: "En revisión",
    needs_fix: "Necesita corrección",
    accepted: "Aceptado",
  } as Record<string, string>,
  upload: "Subir",
  replace: "Reemplazar",
  apostille: "Requiere apostilla",
  translation: "Requiere traducción jurada",
  validity: (days: number) => `Validez de ${days} días — pide con la secuencia en mente`,
  perDependent: "Uno por cada familiar",
  formLabel: "Formulario de solicitud",
  feeLabel: "Tasa oficial",
  reviewNote: "Los documentos subidos entran en cola de validación. Las comprobaciones automáticas llegan en la próxima versión — durante la beta los revisa nuestro equipo.",
  vaultNote: "Los archivos se guardan cifrados en un centro de datos de la UE (Fráncfort), en una carpeta privada a la que solo accede tu cuenta. Si borras tu cuenta, todo desaparece con ella.",
  signOut: "Cerrar sesión",
  deleteDoc: "Quitar",
  supervised: "Checklist v2026-07 · mantenida bajo supervisión colegiada",
  backHome: "Volver a luma.legal",
};

export const appStrings: Record<Locale, typeof en> = { en, es };
export type AppStrings = typeof en;
